apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch
  namespace: default
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: Elasticsearch
      type: elasticsearch
      url: 'http://foundation-elasticsearch-client:9200'
      version: 1
  name: elasticsearch.yaml
