apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: elasticsearch
  namespace: default
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        esVersion: 5
        logLevelField: ""
        logMessageField: ""
        maxConcurrentShardRequests: 256
        timeField: "@timestamp"
        timeInterval: 5s        
      name: Elasticsearch
      type: elasticsearch
      url: 'http://foundation-elasticsearch-client:9200'
      version: 1
  name: elasticsearch.yaml
