branches:
  only:
  - master
language: python
python:
- '3.8'
- '3.9'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: IvAs9XdBkKADUqZL/LstBYkKgWjHtd3DHo0ubuPRRpCjk1A0I5sGIT/l0A0lA+hP8+YK5AbqLeyBmwTr++DwNMxdZfLPT8W/Pnevhd8ZXT46a03rla6PfcDZ9PyfGcW6KFPe/AqSVp46ZTiN1MIiF1l56CzvJlZYQBhOmgvW93IcCpJUNVicqEAzwWMWw1QRIgPhee5ZZ458K5LG2I0RVSbx1L6P9FgX7BEAxeNvzfFnFzU5UFdldB9Tda1OOV8j6a63IhFWwQ6NG+nN1VrmujFpSp3CLWPensP1tNI19u9sAy9HXFi8o5WO7ZUB793gdWl7tNh/Bz38BAU/xe/lNYjjxEQNqBCiFkns56ZKSh800IIXjcKMY8I+nketQ20WIXZg8JvpQc4W+2Lh2ZGt+ashYfeUgD/z2ypz/88xZCxPcis86PZvpGrMGA9y/lRcRoUHw+imfMbbegu0dJzxVxmdtxbT6okw7U7FP5sBggLqr5gjt6TNduyHmcxaaJMbxp9JZlcJstGb3tqh0K9fvEfXPaL5vEv5WybMfDzHQpRybnU/8hpt6dTgPyJ6sL07pbUdcF4r1t890UdV/kJ7eGXGqnjqNxbxpMeij8JVMVY3F9tUJHsMQuUCRO800L0YlglYtx2d4410dCtuHe/mes6rScnk8wR1+PTHXHo1O6c=
