---
application:
  port: 8294
  ssl:
    enabled: True
    cert_dir: /var/kubedriver/certs

messaging:
  connection_address: kafka:9092
  # timeout waiting for initial version check on Kafka producer/consumer initialisation
  # 5000ms is usually sufficient, increase if problems with NoBrokersAvailable occur
  api_version_auto_timeout_ms: 5000

bootstrap:
  templating:
    # Providing our own
    resource_context_service_enabled: False

kegd:
  ready_checks:
    default_max_attempts: 10
    default_timeout_seconds: 300
    default_interval_seconds: 5
    max_timeout_seconds: 3600

resource_driver:
  keep_files: False
  keep_kegdrs: False