---
application:
  port: 8294
  ssl:
    enabled: True
    cert_dir: /var/kubedriver/certs

messaging:
  connection_address: kafka:9092

bootstrap:
  templating:
    # Providing our own
    resource_context_service_enabled: False