apiVersion: v1
kind: Service
metadata:
  name: kubedriver
  labels:
    app: kubedriver
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8294
    targetPort: 8294
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: TCP
    name: http
  selector:
    app: kubedriver